_target_: src.models.cifar10_module.CIFAR10LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.02
  weight_decay: 0.0

net:
  _target_: timm.create_model
  pretrained: true
  num_classes: 10
  model_name: resnet18
