# @package _global_

defaults:
  - _self_
  - datamodule: cifar10.yaml
  - model: cifar10.yaml # very important
  - callbacks: default.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - experiment: cifar.yaml

task_name: "demo"

# checkpoint is necessary for demo
ckpt_path: ???